# Generated by Django 4.0.3 on 2022-03-10 19:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stack', '0002_answer_author_answer_body_answer_date_added_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='up_votes',
            field=models.ManyToManyField(related_name='upvotes', to=settings.AUTH_USER_MODEL),
        ),
    ]
