# Generated by Django 4.0.3 on 2022-03-10 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stack', '0003_answer_up_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
