# Generated by Django 4.0.3 on 2022-03-12 07:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stack', '0004_question_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='up_votes',
            field=models.ManyToManyField(null=True, related_name='upvotes', to=settings.AUTH_USER_MODEL),
        ),
    ]
