# Generated by Django 4.0.3 on 2022-03-13 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stack', '0006_alter_answer_up_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='up_votes',
        ),
        migrations.AddField(
            model_name='answer',
            name='is_helpful',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
