# Generated by Django 4.0.3 on 2022-03-13 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stack', '0007_remove_answer_up_votes_answer_is_helpful'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='is_helpful',
            new_name='is_answer_helpful',
        ),
    ]
